config/routes.rb
Rails.application.routes.draw do
  get '/home', to: 'posts#home'
  resources :posts do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true,
  length: {maximum: 140, minimum: 1}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def home
  end

  def index
    @posts = Post.all
  end

  def show
    redirect_to posts_path
  end

  def new
    if params.has_key?('post')
      @post = Post.new(posts_params)
    else
      @post = Post.new
    end
  end

  def create
    @post = Post.new(posts_params)
    if @post.save
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def edit
    set_post
  end

  def update
    set_post
    if @post.update(posts_params)
      redirect_to posts_path
    else
      render 'edit'
    end
  end

  def destroy
    set_post
    @post.destroy
  redirect_to posts_path
  end

  def confirm
    @post = Post.new(params.require(:post).permit(:content))
    render 'new' if @post.invalid?
  end

  private
  def posts_params
    params.require(:post).permit(:content)
  end
  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def new_or_edit
  if action_name == 'new' || action_name == 'confirm'
    confirm_posts_path
  elsif action_name == 'edit'
    post_path
  end
end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TweetApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <ul class="header_menu clearfix">
        <li><%= link_to 'TweetApp', home_path %></li>
        <li><%= link_to '投稿一覧へ', posts_path %></li>
        <li><%= link_to '新規投稿する', new_post_path %></li>
      </ul>
    </header>
    <%= yield %>
    <footer>
      <h2>TweetAppなら、誰でも手軽に投稿できます。</h2>
    </footer>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="form_container">
<%= form_with(model: @post, local: true, url:new_or_edit) do |form| %>
  <% if @post.errors.any? %>
  <% @post.errors.full_messages.each do |msg| %>
    <ul>
      <li style="color: firebrick"><%= msg %></li>
    </ul>
  <% end %>
  <% end %>
  <%= form.text_area :content, size: "30x5"%>
  <div class="submit_button"><%= form.submit%></div>
<% end %>
</div>

app/views/posts/confirm.html.erb
<h3 class="page_title">以下の内容で登録しても良いですか？</h3>
<%= form_with(model: @post, local: true) do |form| %>
  <%= form.hidden_field :content %>
  <div class="post_container">
    <%= @post.content %>
  </div>
  <div class="confirm_menu">
    <%= form.submit %>
    <br>
    <%= link_to '戻る', new_post_path(params: {post: {content: @post.content}}) %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h3 class="page_title">投稿を編集します</h3>
<%= render 'form'%>

app/views/posts/home.html.erb
<div class='foo'>
<div class="home_page_wrapper">
  <h1>TweetApp</h1>
</div>
</div>

app/views/posts/index.html.erb
<h3 class="page_title">投稿一覧</h3>
<div class='post_wrapper'>
  <% @posts.each do |post| %>
    <div class="post_container">
      <div class="content_area">
        <%= post.content %>
      </div>
      <div class="edit_destroy_nav">
        <span><%= link_to "編集", edit_post_path(post.id) %></span>
        <span><%= link_to "削除", post_path(post.id), method: :delete %></span>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<h3 class="page_title">新規投稿をします</h3>
<%= render 'form' %>